changelog:
  exclude:
    labels:
      - skip-changelog
  categories:
    - title: Security fixes
      labels:
        - security
    - title: Major features
      labels:
        - feature
        - enhancement
    - title: Fixes
      labels:
        - bug
        - fix
    - title: Other changes
      labels:
        - "*"
