include(${CMAKE_CURRENT_LIST_DIR}/Desktop.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/Linux.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/MacOS.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/Windows.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/WebOS.cmake)

macro(jellyfin_resolve_platform_dependencies)
    if(JELLYFIN_NATIVE_WEBOS)
        jellyfin_resolve_webos_dependencies()
    elseif(WIN32)
        jellyfin_resolve_windows_dependencies()
    elseif(APPLE)
        jellyfin_resolve_macos_dependencies()
    else()
        jellyfin_resolve_linux_dependencies()
    endif()
endmacro()

function(jellyfin_configure_platform_targets native_target core_target)
    if(JELLYFIN_NATIVE_WEBOS)
        jellyfin_configure_webos_targets(${native_target} ${core_target})
        return()
    endif()

    jellyfin_add_desktop_sources(${native_target} ${core_target})
    if(WIN32)
        jellyfin_configure_windows_targets(${native_target} ${core_target})
    elseif(APPLE)
        jellyfin_configure_macos_targets(${native_target} ${core_target})
    else()
        jellyfin_configure_linux_targets(${native_target} ${core_target})
    endif()
endfunction()

function(jellyfin_import_static_platform_plugins native_target)
    if(JELLYFIN_NATIVE_WEBOS)
        jellyfin_import_static_webos_plugins(${native_target})
    else()
        find_library(XKBCOMMON_LIB xkbcommon REQUIRED)
        target_link_libraries(${native_target} PRIVATE ${XKBCOMMON_LIB})
    endif()
endfunction()
