/* Client protocol glue for the webOS text_model protocol (see text.xml in
 * this directory for the authoritative opcode order, extracted from LG C2
 * webOS TV 9.2.1 firmware).
 *
 * Hand-written against the classic libwayland-client marshal API
 * (wl_proxy_marshal / wl_proxy_marshal_constructor) because the webOS SDK
 * sysroot ships wayland 1.11, which predates the wl_proxy_marshal_flags API
 * that current wayland-scanner emits. The interface/message tables live in
 * wayland-text-client-protocol.c (generated by wayland-scanner, data only).
 *
 * Copyright © 2012 Intel Corporation
 * Copyright © 2013-2020 LG Electronics, Inc.
 * SPDX-License-Identifier: MIT
 */

#ifndef TEXT_CLIENT_PROTOCOL_H
#define TEXT_CLIENT_PROTOCOL_H

#include <stdint.h>
#include <stddef.h>
#include "wayland-client.h"

#ifdef __cplusplus
extern "C" {
#endif

struct wl_seat;
struct wl_surface;
struct text_model;
struct text_model_factory;

extern const struct wl_interface text_model_interface;
extern const struct wl_interface text_model_factory_interface;

#ifndef TEXT_MODEL_CONTENT_HINT_ENUM
#define TEXT_MODEL_CONTENT_HINT_ENUM
/**
 * text_model_content_hint - content hint
 *
 * Content hint is a bitmask to allow to modify the behavior of the text
 * input.
 */
enum text_model_content_hint {
	TEXT_MODEL_CONTENT_HINT_NONE = 0x0,
	TEXT_MODEL_CONTENT_HINT_DEFAULT = 0x7,
	TEXT_MODEL_CONTENT_HINT_PASSWORD = 0xc0,
	TEXT_MODEL_CONTENT_HINT_AUTO_COMPLETION = 0x1,
	TEXT_MODEL_CONTENT_HINT_AUTO_CORRECTION = 0x2,
	TEXT_MODEL_CONTENT_HINT_AUTO_CAPITALIZATION = 0x4,
	TEXT_MODEL_CONTENT_HINT_LOWERCASE = 0x8,
	TEXT_MODEL_CONTENT_HINT_UPPERCASE = 0x10,
	TEXT_MODEL_CONTENT_HINT_TITLECASE = 0x20,
	TEXT_MODEL_CONTENT_HINT_HIDDEN_TEXT = 0x40,
	TEXT_MODEL_CONTENT_HINT_SENSITIVE_DATA = 0x80,
	TEXT_MODEL_CONTENT_HINT_LATIN = 0x100,
	TEXT_MODEL_CONTENT_HINT_MULTILINE = 0x200,
};
#endif /* TEXT_MODEL_CONTENT_HINT_ENUM */

#ifndef TEXT_MODEL_CONTENT_PURPOSE_ENUM
#define TEXT_MODEL_CONTENT_PURPOSE_ENUM
/**
 * text_model_content_purpose - content purpose
 *
 * The content purpose allows to specify the primary purpose of a text
 * input.
 */
enum text_model_content_purpose {
	TEXT_MODEL_CONTENT_PURPOSE_NORMAL = 0,
	TEXT_MODEL_CONTENT_PURPOSE_ALPHA = 1,
	TEXT_MODEL_CONTENT_PURPOSE_DIGITS = 2,
	TEXT_MODEL_CONTENT_PURPOSE_NUMBER = 3,
	TEXT_MODEL_CONTENT_PURPOSE_PHONE = 4,
	TEXT_MODEL_CONTENT_PURPOSE_URL = 5,
	TEXT_MODEL_CONTENT_PURPOSE_EMAIL = 6,
	TEXT_MODEL_CONTENT_PURPOSE_NAME = 7,
	TEXT_MODEL_CONTENT_PURPOSE_PASSWORD = 8,
	TEXT_MODEL_CONTENT_PURPOSE_DATE = 9,
	TEXT_MODEL_CONTENT_PURPOSE_TIME = 10,
	TEXT_MODEL_CONTENT_PURPOSE_DATETIME = 11,
	TEXT_MODEL_CONTENT_PURPOSE_TERMINAL = 12,
};
#endif /* TEXT_MODEL_CONTENT_PURPOSE_ENUM */

#ifndef TEXT_MODEL_ENTER_KEY_TYPE_ENUM
#define TEXT_MODEL_ENTER_KEY_TYPE_ENUM
/**
 * text_model_enter_key_type - enter key type
 *
 * Alters the appearance of the enter key on the input panel.
 */
enum text_model_enter_key_type {
	TEXT_MODEL_ENTER_KEY_TYPE_DEFAULT = 0,
	TEXT_MODEL_ENTER_KEY_TYPE_RETURN = 1,
	TEXT_MODEL_ENTER_KEY_TYPE_DONE = 2,
	TEXT_MODEL_ENTER_KEY_TYPE_GO = 3,
	TEXT_MODEL_ENTER_KEY_TYPE_SEND = 4,
	TEXT_MODEL_ENTER_KEY_TYPE_SEARCH = 5,
	TEXT_MODEL_ENTER_KEY_TYPE_NEXT = 6,
	TEXT_MODEL_ENTER_KEY_TYPE_PREVIOUS = 7,
};
#endif /* TEXT_MODEL_ENTER_KEY_TYPE_ENUM */

#ifndef TEXT_MODEL_PREEDIT_STYLE_ENUM
#define TEXT_MODEL_PREEDIT_STYLE_ENUM
/**
 * text_model_preedit_style - pre-edit style
 *
 * The style for a composing text.
 */
enum text_model_preedit_style {
	TEXT_MODEL_PREEDIT_STYLE_DEFAULT = 1,
	TEXT_MODEL_PREEDIT_STYLE_ACTIVE = 2,
	TEXT_MODEL_PREEDIT_STYLE_INACTIVE = 3,
	TEXT_MODEL_PREEDIT_STYLE_HIGHLIGHT = 4,
	TEXT_MODEL_PREEDIT_STYLE_UNDERLINE = 5,
	TEXT_MODEL_PREEDIT_STYLE_SELECTION = 6,
	TEXT_MODEL_PREEDIT_STYLE_INCORRECT = 7,
};
#endif /* TEXT_MODEL_PREEDIT_STYLE_ENUM */

/**
 * text_model_listener - text model events
 *
 * Member order defines wire opcodes; must match text.xml.
 */
struct text_model_listener {
	void (*commit_string)(void *data,
			      struct text_model *text_model,
			      uint32_t serial,
			      const char *text);
	void (*preedit_string)(void *data,
			       struct text_model *text_model,
			       uint32_t serial,
			       const char *text,
			       const char *commit);
	void (*delete_surrounding_text)(void *data,
					struct text_model *text_model,
					uint32_t serial,
					int32_t index,
					uint32_t length);
	void (*cursor_position)(void *data,
				struct text_model *text_model,
				uint32_t serial,
				int32_t index,
				int32_t anchor);
	void (*preedit_styling)(void *data,
				struct text_model *text_model,
				uint32_t serial,
				uint32_t index,
				uint32_t length,
				uint32_t style);
	void (*preedit_cursor)(void *data,
			       struct text_model *text_model,
			       uint32_t serial,
			       int32_t index);
	void (*modifiers_map)(void *data,
			      struct text_model *text_model,
			      struct wl_array *map);
	void (*keysym)(void *data,
		       struct text_model *text_model,
		       uint32_t serial,
		       uint32_t time,
		       uint32_t sym,
		       uint32_t state,
		       uint32_t modifiers);
	void (*enter)(void *data,
		      struct text_model *text_model,
		      struct wl_surface *surface);
	void (*leave)(void *data,
		      struct text_model *text_model);
	void (*input_panel_state)(void *data,
				  struct text_model *text_model,
				  uint32_t state);
	void (*input_panel_rect)(void *data,
				 struct text_model *text_model,
				 int32_t x,
				 int32_t y,
				 uint32_t width,
				 uint32_t height);
};

static inline int
text_model_add_listener(struct text_model *text_model,
			const struct text_model_listener *listener, void *data)
{
	return wl_proxy_add_listener((struct wl_proxy *) text_model,
				     (void (**)(void)) listener, data);
}

/* Request opcodes: LG C2 firmware order (see text.xml). */
#define TEXT_MODEL_SET_SURROUNDING_TEXT 0
#define TEXT_MODEL_ACTIVATE 1
#define TEXT_MODEL_DEACTIVATE 2
#define TEXT_MODEL_RESET 3
#define TEXT_MODEL_SET_CURSOR_RECTANGLE 4
#define TEXT_MODEL_SET_CONTENT_TYPE 5
#define TEXT_MODEL_SET_ENTER_KEY_TYPE 6
#define TEXT_MODEL_INVOKE_ACTION 7
#define TEXT_MODEL_COMMIT 8
#define TEXT_MODEL_SET_MAX_TEXT_LENGTH 9
#define TEXT_MODEL_SET_PLATFORM_DATA 10
#define TEXT_MODEL_SHOW_INPUT_PANEL 11
#define TEXT_MODEL_HIDE_INPUT_PANEL 12
#define TEXT_MODEL_SET_INPUT_PANEL_RECT 13
#define TEXT_MODEL_RESET_INPUT_PANEL_RECT 14

static inline void
text_model_set_user_data(struct text_model *text_model, void *user_data)
{
	wl_proxy_set_user_data((struct wl_proxy *) text_model, user_data);
}

static inline void *
text_model_get_user_data(struct text_model *text_model)
{
	return wl_proxy_get_user_data((struct wl_proxy *) text_model);
}

static inline void
text_model_destroy(struct text_model *text_model)
{
	wl_proxy_destroy((struct wl_proxy *) text_model);
}

static inline void
text_model_set_surrounding_text(struct text_model *text_model, const char *text, uint32_t cursor, uint32_t anchor)
{
	wl_proxy_marshal((struct wl_proxy *) text_model,
			 TEXT_MODEL_SET_SURROUNDING_TEXT, text, cursor, anchor);
}

static inline void
text_model_activate(struct text_model *text_model, uint32_t serial, struct wl_seat *seat, struct wl_surface *surface)
{
	wl_proxy_marshal((struct wl_proxy *) text_model,
			 TEXT_MODEL_ACTIVATE, serial, seat, surface);
}

static inline void
text_model_deactivate(struct text_model *text_model, struct wl_seat *seat)
{
	wl_proxy_marshal((struct wl_proxy *) text_model,
			 TEXT_MODEL_DEACTIVATE, seat);
}

static inline void
text_model_reset(struct text_model *text_model, uint32_t serial)
{
	wl_proxy_marshal((struct wl_proxy *) text_model,
			 TEXT_MODEL_RESET, serial);
}

static inline void
text_model_set_cursor_rectangle(struct text_model *text_model, int32_t x, int32_t y, int32_t width, int32_t height)
{
	wl_proxy_marshal((struct wl_proxy *) text_model,
			 TEXT_MODEL_SET_CURSOR_RECTANGLE, x, y, width, height);
}

static inline void
text_model_set_content_type(struct text_model *text_model, uint32_t hint, uint32_t purpose)
{
	wl_proxy_marshal((struct wl_proxy *) text_model,
			 TEXT_MODEL_SET_CONTENT_TYPE, hint, purpose);
}

static inline void
text_model_set_enter_key_type(struct text_model *text_model, uint32_t enter_key_type)
{
	wl_proxy_marshal((struct wl_proxy *) text_model,
			 TEXT_MODEL_SET_ENTER_KEY_TYPE, enter_key_type);
}

static inline void
text_model_invoke_action(struct text_model *text_model, uint32_t button, uint32_t index)
{
	wl_proxy_marshal((struct wl_proxy *) text_model,
			 TEXT_MODEL_INVOKE_ACTION, button, index);
}

static inline void
text_model_commit(struct text_model *text_model)
{
	wl_proxy_marshal((struct wl_proxy *) text_model,
			 TEXT_MODEL_COMMIT);
}

static inline void
text_model_set_max_text_length(struct text_model *text_model, uint32_t length)
{
	wl_proxy_marshal((struct wl_proxy *) text_model,
			 TEXT_MODEL_SET_MAX_TEXT_LENGTH, length);
}

static inline void
text_model_set_platform_data(struct text_model *text_model, const char *text)
{
	wl_proxy_marshal((struct wl_proxy *) text_model,
			 TEXT_MODEL_SET_PLATFORM_DATA, text);
}

static inline void
text_model_show_input_panel(struct text_model *text_model)
{
	wl_proxy_marshal((struct wl_proxy *) text_model,
			 TEXT_MODEL_SHOW_INPUT_PANEL);
}

static inline void
text_model_hide_input_panel(struct text_model *text_model)
{
	wl_proxy_marshal((struct wl_proxy *) text_model,
			 TEXT_MODEL_HIDE_INPUT_PANEL);
}

static inline void
text_model_set_input_panel_rect(struct text_model *text_model, int32_t x, int32_t y, uint32_t width, uint32_t height)
{
	wl_proxy_marshal((struct wl_proxy *) text_model,
			 TEXT_MODEL_SET_INPUT_PANEL_RECT, x, y, width, height);
}

static inline void
text_model_reset_input_panel_rect(struct text_model *text_model)
{
	wl_proxy_marshal((struct wl_proxy *) text_model,
			 TEXT_MODEL_RESET_INPUT_PANEL_RECT);
}

#define TEXT_MODEL_FACTORY_CREATE_TEXT_MODEL 0

static inline void
text_model_factory_set_user_data(struct text_model_factory *text_model_factory, void *user_data)
{
	wl_proxy_set_user_data((struct wl_proxy *) text_model_factory, user_data);
}

static inline void *
text_model_factory_get_user_data(struct text_model_factory *text_model_factory)
{
	return wl_proxy_get_user_data((struct wl_proxy *) text_model_factory);
}

static inline void
text_model_factory_destroy(struct text_model_factory *text_model_factory)
{
	wl_proxy_destroy((struct wl_proxy *) text_model_factory);
}

static inline struct text_model *
text_model_factory_create_text_model(struct text_model_factory *text_model_factory)
{
	struct wl_proxy *id;

	id = wl_proxy_marshal_constructor((struct wl_proxy *) text_model_factory,
					  TEXT_MODEL_FACTORY_CREATE_TEXT_MODEL,
					  &text_model_interface, NULL);

	return (struct text_model *) id;
}

#ifdef __cplusplus
}
#endif

#endif /* TEXT_CLIENT_PROTOCOL_H */
