/* Generated by wayland-scanner 1.24.0 */

/*
 * Copyright © 2012 Intel Corporation
 * Copyright © 2013-2020 LG Electronics, Inc.
 *
 * Permission to use, copy, modify, distribute, and sell this
 * software and its documentation for any purpose is hereby granted
 * without fee, provided that the above copyright notice appear in
 * all copies and that both that copyright notice and this permission
 * notice appear in supporting documentation, and that the name of
 * the copyright holders not be used in advertising or publicity
 * pertaining to distribution of the software without specific,
 * written prior permission.  The copyright holders make no
 * representations about the suitability of this software for any
 * purpose.  It is provided "as is" without express or implied
 * warranty.
 *
 * THE COPYRIGHT HOLDERS DISCLAIM ALL WARRANTIES WITH REGARD TO THIS
 * SOFTWARE, INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND
 * FITNESS, IN NO EVENT SHALL THE COPYRIGHT HOLDERS BE LIABLE FOR ANY
 * SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN
 * AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
 * ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF
 * THIS SOFTWARE.
 */

#include <stdbool.h>
#include <stdlib.h>
#include <stdint.h>
#include "wayland-util.h"

#ifndef __has_attribute
# define __has_attribute(x) 0  /* Compatibility with non-clang compilers. */
#endif

#if (__has_attribute(visibility) || defined(__GNUC__) && __GNUC__ >= 4)
#define WL_PRIVATE __attribute__ ((visibility("hidden")))
#else
#define WL_PRIVATE
#endif

extern const struct wl_interface text_model_interface;
extern const struct wl_interface wl_seat_interface;
extern const struct wl_interface wl_surface_interface;

static const struct wl_interface *text_types[] = {
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	&wl_seat_interface,
	&wl_surface_interface,
	&wl_seat_interface,
	&wl_surface_interface,
	&text_model_interface,
};

static const struct wl_message text_model_requests[] = {
	{ "set_surrounding_text", "suu", text_types + 0 },
	{ "activate", "uoo", text_types + 5 },
	{ "deactivate", "o", text_types + 8 },
	{ "reset", "u", text_types + 0 },
	{ "set_cursor_rectangle", "iiii", text_types + 0 },
	{ "set_content_type", "uu", text_types + 0 },
	{ "set_enter_key_type", "u", text_types + 0 },
	{ "invoke_action", "uu", text_types + 0 },
	{ "commit", "", text_types + 0 },
	{ "set_max_text_length", "u", text_types + 0 },
	{ "set_platform_data", "s", text_types + 0 },
	{ "show_input_panel", "", text_types + 0 },
	{ "hide_input_panel", "", text_types + 0 },
	{ "set_input_panel_rect", "iiuu", text_types + 0 },
	{ "reset_input_panel_rect", "", text_types + 0 },
};

static const struct wl_message text_model_events[] = {
	{ "commit_string", "us", text_types + 0 },
	{ "preedit_string", "uss", text_types + 0 },
	{ "delete_surrounding_text", "uiu", text_types + 0 },
	{ "cursor_position", "uii", text_types + 0 },
	{ "preedit_styling", "uuuu", text_types + 0 },
	{ "preedit_cursor", "ui", text_types + 0 },
	{ "modifiers_map", "a", text_types + 0 },
	{ "keysym", "uuuuu", text_types + 0 },
	{ "enter", "o", text_types + 9 },
	{ "leave", "", text_types + 0 },
	{ "input_panel_state", "u", text_types + 0 },
	{ "input_panel_rect", "iiuu", text_types + 0 },
};

WL_PRIVATE const struct wl_interface text_model_interface = {
	"text_model", 1,
	15, text_model_requests,
	12, text_model_events,
};

static const struct wl_message text_model_factory_requests[] = {
	{ "create_text_model", "n", text_types + 10 },
};

WL_PRIVATE const struct wl_interface text_model_factory_interface = {
	"text_model_factory", 1,
	1, text_model_factory_requests,
	0, NULL,
};

