#!/bin/sh

APP_ID="com.sachk.tern"

rm -f "/var/palm/ls2-dev/roles/pub/$APP_ID.json"
rm -f "/var/palm/ls2-dev/roles/prv/$APP_ID.json"
for LEGACY in \
  "/var/luna-service2/roles.d/$APP_ID.app.json" \
  "/var/luna-service2/client-permissions.d/$APP_ID.app.json" \
  "/var/luna-service2/manifests.d/$APP_ID.manifest.json"; do
  rm -f "$LEGACY"
done

ls2-control scan-services 2>/dev/null || true

exit 0
