#include "platform/webos/WebOSSelfUpdateProbe.h"

#include <QByteArray>
#include <QDir>
#include <QFile>
#include <QFileInfo>
#include <QTimer>
#include <QtGlobal>

#include <memory>
#include <vector>

extern "C" {
#include <luna-service2/lunaservice.h>
#include <webos-helpers/libhelpers.h>
}

namespace JellyfinNative {
namespace {

    // What the probe asks to install. The device script serves a real IPK over
    // HTTP from the machine running it and bakes the URL in here, so a refusal
    // is about permission and not about a missing file: this is the same shape
    // a real self-update would take.
    QByteArray probeTarget()
    {
        const QByteArray fromEnvironment = qgetenv("SPOOL_SELFUPDATE_PROBE_TARGET");
        if (!fromEnvironment.isEmpty())
            return fromEnvironment;
#if defined(SPOOL_WEBOS_SELFUPDATE_PROBE_TARGET)
        return QByteArrayLiteral(SPOOL_WEBOS_SELFUPDATE_PROBE_TARGET);
#else
        return QByteArrayLiteral("/tmp/spool-selfupdate-probe.ipk");
#endif
    }

    struct Attempt {
        const char *label;
        const char *uri;
        QByteArray payload;
        // A call that should succeed for any app. If one of these is denied
        // too, the probe itself is wrong and the install denials say nothing.
        bool control = false;
    };

    // Every reply is printed as it arrived. The interesting part is which of
    // the two kinds of failure it is, so nothing here summarises.
    struct AttemptState {
        QByteArray label;
        std::unique_ptr<HContext> context;
    };

    std::vector<std::unique_ptr<AttemptState>>& attempts()
    {
        static std::vector<std::unique_ptr<AttemptState>> value;
        return value;
    }

    // The header calls the third argument userdata, and what arrives is the
    // HContext. Rather than depend on which, look the pointer up as both --
    // the labels came out as garbage bytes when this trusted the name.
    bool onReply(LSHandle *, LSMessage *message, void *ctx)
    {
        const char *label = "?";
        for (const auto& state : attempts()) {
            if (state.get() == ctx || state->context.get() == ctx) {
                label = state->label.constData();
                break;
            }
        }
        const char *payload = message ? LSMessageGetPayload(message) : nullptr;
        qInfo("selfupdate-probe: %s <- %s", label, payload ? payload : "(no payload)");
        return true;
    }

    void run(const Attempt& attempt)
    {
        auto state = std::make_unique<AttemptState>();
        state->label = QByteArray(attempt.label);
        state->context = std::make_unique<HContext>();
        state->context->pub = true;
        state->context->multiple = true;
        state->context->callback = &onReply;
        state->context->userdata = state.get();

        qInfo("selfupdate-probe: %s -> %s %s", attempt.label, attempt.uri, attempt.payload.constData());
        HContext *context = state->context.get();
        // Registered before the call, because a reply can arrive before this
        // function returns and the callback resolves its label from here.
        attempts().push_back(std::move(state));
        const int result = HLunaServiceCall(attempt.uri, attempt.payload.constData(), context);
        if (result != 0) {
            // A non-zero return is the bus refusing to dispatch at all, which
            // is itself an answer: the call never reached the service.
            qInfo("selfupdate-probe: %s !! HLunaServiceCall returned %d (call not dispatched)", attempt.label, result);
        }
    }

    // What the bus thinks this app is allowed to do. On a set installed
    // through developer mode these are generated by appinstalld's rolegen, so
    // reading them back says what was actually granted rather than what the
    // package asked for.
    void reportGrantedRole()
    {
        const QStringList roots {
            QStringLiteral("/var/palm/ls2-dev/roles/pub"),
            QStringLiteral("/var/palm/ls2-dev/roles/prv"),
            QStringLiteral("/var/palm/ls2-dev/client-permissions.d"),
            QStringLiteral("/var/palm/ls2-dev/api-permissions.d"),
            QStringLiteral("/var/palm/ls2/roles/pub"),
        };
        for (const QString& root : roots) {
            QDir directory(root);
            if (!directory.exists()) {
                qInfo("selfupdate-probe: role dir %s absent", qPrintable(root));
                continue;
            }
            const QStringList entries = directory.entryList({ QStringLiteral("*spool*") }, QDir::Files);
            if (entries.isEmpty()) {
                qInfo("selfupdate-probe: role dir %s has no entry for this app (%lld other files)", qPrintable(root),
                    static_cast<long long>(directory.entryList(QDir::Files).size()));
                continue;
            }
            for (const QString& entry : entries) {
                QFile file(directory.filePath(entry));
                if (!file.open(QIODevice::ReadOnly)) {
                    qInfo("selfupdate-probe: role %s unreadable", qPrintable(file.fileName()));
                    continue;
                }
                qInfo("selfupdate-probe: role %s = %s", qPrintable(file.fileName()), file.readAll().constData());
            }
        }
    }

} // namespace

void startSelfUpdateProbe()
{
    QTimer::singleShot(5000, [] {
        const QByteArray ipk = probeTarget();
        const bool remote = ipk.startsWith("http");
        qInfo("selfupdate-probe: begin; target %s (%s)", ipk.constData(),
            remote ? "url"
                   : (QFileInfo::exists(QString::fromLocal8Bit(ipk)) ? "local file present" : "local file MISSING"));
        reportGrantedRole();

        const QByteArray installPayload = QByteArrayLiteral(R"({"id":"com.sachk.spool","ipkUrl":")") + ipk
            + QByteArrayLiteral(R"(","subscribe":true})");

        const std::vector<Attempt> plan {
            // Controls first, so a blanket denial is obvious before anything
            // is read into the install results.
            { "control/listLaunchPoints", "luna://com.webos.applicationManager/listLaunchPoints",
                QByteArrayLiteral(R"({"subscribe":false})"), true },
            { "control/getAppInfo", "luna://com.webos.service.applicationmanager/getAppInfo",
                QByteArrayLiteral(R"({"id":"com.sachk.spool"})"), true },
            // The developer-mode install path, which is what ares-install
            // drives from outside. If anything works unrooted, it is this.
            { "appInstallService/dev/install", "luna://com.webos.appInstallService/dev/install", installPayload },
            // The production path, expected to be privileged. Included so the
            // difference between the two is on the record.
            { "appInstallService/install", "luna://com.webos.appInstallService/install", installPayload },
            // Homebrew Channel, if it is installed. It runs without root, so
            // an app that may call it can update through it.
            { "hbchannel/install", "luna://org.webosbrew.hbchannel.service/install",
                QByteArrayLiteral(R"({"ipkUrl":")") + ipk + QByteArrayLiteral(R"(","subscribe":true})") },
        };

        for (const Attempt& attempt : plan)
            run(attempt);

        // Long enough for a denial, which is immediate, and for a real install
        // to have said something about progress.
        QTimer::singleShot(20000, [] { qInfo("selfupdate-probe: end"); });
    });
}

} // namespace JellyfinNative
