name: publish Nix cache

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: publish-nix-cache-${{ github.ref }}
  cancel-in-progress: true

jobs:
  native:
    name: Native package (${{ matrix.arch }})
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: x86_64-linux
            runner: ubuntu-24.04
          - arch: aarch64-darwin
            runner: macos-14
          - arch: x86_64-darwin
            runner: macos-15-intel

    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.0.2
        with:
          submodules: recursive

      - uses: nixbuild/nix-quick-install-action@2c9db80fb984ceb1bcaa77cdda3fdf8cfba92035 # v34
        with:
          nix_conf: |
            experimental-features = nix-command flakes
            connect-timeout = 30
            download-attempts = 5

      - uses: cachix/cachix-action@3ba601ff5bbb07c7220846facfa2cd81eeee15a1 # v16
        with:
          name: spool
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Build and publish tailored Qt
        run: nix build --accept-flake-config .#native-qt-cache --print-build-logs
      - name: Build and publish native package
        run: nix build --accept-flake-config .#native-cache --print-build-logs
